/**
 * Local areas the business can publish pages for. ONE place to add, remove or
 * disable an area (`enabled: false` hides its pages everywhere: routes, sitemap,
 * internal links). Only publish areas you genuinely cover.
 *
 * Content rules (so the pages stay useful, accurate and non-spammy):
 *  - Only well-known, stable local facts. No statistics, no reviews, no claims
 *    about where cleaners live. Stations are listed only where certain.
 *  - Every field is written per area — pages must not read like a find-and-replace.
 */

export type AreaTag = "rental" | "family" | "period" | "interwar" | "newbuild" | "flats" | "leafy" | "centre" | "commuter" | "estate" | "village";
export type AreaGroup = "Barking & Dagenham" | "Romford & Havering" | "Ilford & Redbridge" | "Newham & East London" | "Essex border";

export interface Area {
  slug: string;
  name: string;
  postcodes: string[];
  group: AreaGroup;
  /** One sentence on what the place is known for. */
  about: string;
  /** One sentence on the typical homes. */
  homes: string;
  /** One sentence connecting the area to a cleaning need. */
  tip: string;
  tags: AreaTag[];
  /** Slugs of genuinely neighbouring areas (internal links). */
  nearby: string[];
  /** Only where certain. */
  station?: string;
  enabled?: boolean;
}

const ALL_AREAS: Area[] = [
  // ── Barking & Dagenham ────────────────────────────────────────────────
  { slug: "barking", name: "Barking", postcodes: ["IG11"], group: "Barking & Dagenham", tags: ["centre", "commuter", "flats", "interwar"],
    about: "Barking is a busy east London town built around Barking Abbey and Barking Park, with one of the best-connected stations in the area.",
    homes: "Victorian and interwar terraces sit alongside purpose-built flats and new riverside apartments.",
    tip: "Mixed housing means every clean is different, so we price by the hour and you choose how long your home needs.",
    nearby: ["upney", "thames-view", "barking-riverside", "becontree", "east-ham"],
    station: "Barking station has District, Hammersmith & City, c2c and London Overground services." },
  { slug: "dagenham", name: "Dagenham", postcodes: ["RM8", "RM9", "RM10"], group: "Barking & Dagenham", tags: ["family", "interwar", "estate"],
    about: "Dagenham is best known for its industrial heritage and the Ford plant, and is today a large, family-oriented part of east London.",
    homes: "Interwar family houses make up much of the area, along with flats near the main roads and stations.",
    tip: "Family homes with busy kitchens and bathrooms are where regular and deep cleans make the biggest difference.",
    nearby: ["becontree", "dagenham-heathway", "dagenham-east", "becontree-heath", "rush-green"],
    station: "Dagenham Heathway and Dagenham East stations are on the District line." },
  { slug: "becontree", name: "Becontree", postcodes: ["RM8", "RM9", "RM10"], group: "Barking & Dagenham", tags: ["family", "interwar", "estate"],
    about: "The Becontree Estate was built in the 1920s and 1930s and is one of the largest housing estates ever built.",
    homes: "Most homes are interwar houses with gardens, many with the original layout of smaller rooms and a separate kitchen.",
    tip: "Older, smaller-roomed houses collect dust and grime in corners and behind radiators, so a deep clean is a popular first step before settling into a regular routine.",
    nearby: ["dagenham", "becontree-heath", "dagenham-heathway", "upney", "chadwell-heath"],
    station: "Becontree station is on the District line." },
  { slug: "chadwell-heath", name: "Chadwell Heath", postcodes: ["RM6"], group: "Barking & Dagenham", tags: ["commuter", "family", "interwar"],
    about: "Chadwell Heath sits on the edge of east London and Essex, with its own high street and a station on the Elizabeth line.",
    homes: "Interwar semis and terraces, plus newer flats close to the station.",
    tip: "Commuters here often want a regular clean on a set day so the house is ready when they get home.",
    nearby: ["goodmayes", "marks-gate", "becontree-heath", "romford", "seven-kings"],
    station: "Chadwell Heath station is on the Elizabeth line." },
  { slug: "becontree-heath", name: "Becontree Heath", postcodes: ["RM8"], group: "Barking & Dagenham", tags: ["family", "interwar", "estate"],
    about: "Becontree Heath is home to Valence House Museum and park, and sits at the centre of the Becontree area.",
    homes: "Interwar family houses are the norm, with flats near the main road.",
    tip: "Older houses with smaller rooms respond well to a deep clean, followed by a regular clean to keep them that way.",
    nearby: ["becontree", "dagenham", "chadwell-heath", "rush-green", "marks-gate"] },
  { slug: "dagenham-heathway", name: "Dagenham Heathway", postcodes: ["RM9", "RM10"], group: "Barking & Dagenham", tags: ["centre", "flats", "rental", "interwar"],
    about: "Dagenham Heathway is the busy shopping parade at the heart of the area, with its own District line station.",
    homes: "A mix of interwar houses and flats above and around the shops.",
    tip: "Flats and shared houses around the parade mean frequent end of tenancy and deep cleaning jobs.",
    nearby: ["dagenham", "becontree", "dagenham-east", "becontree-heath", "upney"],
    station: "Dagenham Heathway station is on the District line." },
  { slug: "dagenham-east", name: "Dagenham East", postcodes: ["RM10"], group: "Barking & Dagenham", tags: ["commuter", "family", "interwar"],
    about: "Dagenham East is a residential neighbourhood with its own District line station, close to Elm Park and Rainham.",
    homes: "Interwar houses and terraces, plus some newer flats.",
    tip: "Commuter households book a regular clean to keep the home fresh around work hours.",
    nearby: ["dagenham", "elm-park", "dagenham-heathway", "rainham", "south-hornchurch"],
    station: "Dagenham East station is on the District line." },
  { slug: "upney", name: "Upney", postcodes: ["IG11"], group: "Barking & Dagenham", tags: ["commuter", "family", "interwar"],
    about: "Upney is a residential neighbourhood near Barking with its own District line station.",
    homes: "Interwar houses and terraces, with flats near the station.",
    tip: "Commuter households tend to book a regular clean to keep the home ready for the evening.",
    nearby: ["barking", "becontree", "thames-view", "barking-riverside", "dagenham-heathway"],
    station: "Upney station is on the District line." },
  { slug: "thames-view", name: "Thames View", postcodes: ["IG11"], group: "Barking & Dagenham", tags: ["newbuild", "family", "rental"],
    about: "Thames View is a residential neighbourhood between Barking and the river, close to the new Barking Riverside development.",
    homes: "Post-war houses and low-rise flats, with new homes nearby.",
    tip: "Moving into or out of newer homes nearby makes after builders and end of tenancy cleans especially common.",
    nearby: ["barking-riverside", "barking", "upney", "becontree", "rainham"] },
  { slug: "barking-riverside", name: "Barking Riverside", postcodes: ["IG11"], group: "Barking & Dagenham", tags: ["newbuild", "flats", "rental"],
    about: "Barking Riverside is a major new neighbourhood on the former power station site, with its own London Overground station.",
    homes: "Modern flats and new-build houses, many being lived in for the first time.",
    tip: "Brand-new homes often need a proper builders' clean before move-in, and rented flats need a thorough end of tenancy clean at the end.",
    nearby: ["thames-view", "barking", "upney", "rainham", "becontree"],
    station: "Barking Riverside station is on the London Overground." },
  { slug: "marks-gate", name: "Marks Gate", postcodes: ["RM6"], group: "Barking & Dagenham", tags: ["family", "estate"],
    about: "Marks Gate is a quiet residential pocket at the northern edge of Barking and Dagenham, near Chadwell Heath.",
    homes: "Largely interwar and post-war houses and low-rise flats.",
    tip: "Practical family homes here benefit from a dependable regular clean on a day that suits your routine.",
    nearby: ["chadwell-heath", "becontree-heath", "rush-green", "goodmayes", "romford"] },

  // ── Romford & Havering ────────────────────────────────────────────────
  { slug: "romford", name: "Romford", postcodes: ["RM1", "RM2", "RM3", "RM7"], group: "Romford & Havering", tags: ["centre", "commuter", "flats", "family"],
    about: "Romford is the main town centre of the area, known for its market and for good Elizabeth line and rail links.",
    homes: "Town-centre flats, Victorian and interwar terraces, and large suburban houses all sit within a short distance.",
    tip: "The range of home types means we tailor the hours to the property rather than offering one-size-fits-all packages.",
    nearby: ["gidea-park", "collier-row", "harold-wood", "squirrels-heath", "rush-green"],
    station: "Romford station is on the Elizabeth line and Greater Anglia services." },
  { slug: "gidea-park", name: "Gidea Park", postcodes: ["RM2"], group: "Romford & Havering", tags: ["leafy", "period", "commuter", "family"],
    about: "Gidea Park is a well-regarded Romford suburb known for its Arts and Crafts garden suburb houses and an Elizabeth line station.",
    homes: "Many homes are distinctive early twentieth-century houses with period features.",
    tip: "Period features such as original windows and woodwork reward careful, thorough cleaning, so a deep clean suits them well.",
    nearby: ["romford", "squirrels-heath", "harold-wood", "emerson-park", "collier-row"],
    station: "Gidea Park station is on the Elizabeth line." },
  { slug: "collier-row", name: "Collier Row", postcodes: ["RM5"], group: "Romford & Havering", tags: ["family", "estate"],
    about: "Collier Row is a residential neighbourhood on the northern side of Romford.",
    homes: "Mostly family houses and semis, along with some low-rise flats.",
    tip: "Family households here book regular cleans to keep up with the weekly rush, and a deep clean when the seasons change.",
    nearby: ["romford", "harold-hill", "gallows-corner", "harold-park", "chadwell-heath"] },
  { slug: "harold-hill", name: "Harold Hill", postcodes: ["RM3"], group: "Romford & Havering", tags: ["estate", "family", "rental"],
    about: "Harold Hill is a large post-war estate built to house families moving out of central London.",
    homes: "Much of the housing is 1950s houses and low-rise flats.",
    tip: "Large family households and rented homes make regular cleans and end of tenancy cleans especially popular.",
    nearby: ["harold-wood", "harold-park", "gallows-corner", "collier-row", "romford"] },
  { slug: "harold-wood", name: "Harold Wood", postcodes: ["RM3"], group: "Romford & Havering", tags: ["commuter", "family", "leafy", "village"],
    about: "Harold Wood is a pleasant suburb with a village feel and an Elizabeth line station.",
    homes: "Houses range from Victorian and Edwardian terraces to 1930s semis.",
    tip: "Commuters and families alike book a regular clean on a set day so the house is ready for the weekend.",
    nearby: ["harold-hill", "harold-park", "gidea-park", "romford", "upminster"],
    station: "Harold Wood station is on the Elizabeth line." },
  { slug: "harold-park", name: "Harold Park", postcodes: ["RM3"], group: "Romford & Havering", tags: ["family", "estate"],
    about: "Harold Park is a residential area on the eastern side of Romford, next to Harold Wood and Harold Hill.",
    homes: "Family houses and some flats.",
    tip: "Busy family homes benefit from a regular clean to keep ahead of the weekly mess.",
    nearby: ["harold-wood", "harold-hill", "gidea-park", "romford", "upminster"] },
  { slug: "gallows-corner", name: "Gallows Corner", postcodes: ["RM3"], group: "Romford & Havering", tags: ["commuter", "flats", "family"],
    about: "Gallows Corner is a well-known road junction on the Romford side of Havering, surrounded by residential streets and retail.",
    homes: "A mix of interwar houses and low-rise flats.",
    tip: "Flats and houses close to the main routes suit regular cleans fitted around commuting hours.",
    nearby: ["romford", "collier-row", "harold-hill", "harold-park", "gidea-park"] },
  { slug: "squirrels-heath", name: "Squirrels Heath", postcodes: ["RM2"], group: "Romford & Havering", tags: ["family", "commuter", "interwar"],
    about: "Squirrels Heath is a residential neighbourhood between Romford and Gidea Park.",
    homes: "Mostly interwar and 1930s houses with gardens.",
    tip: "Family homes close to Gidea Park station suit a regular clean on a set day each week.",
    nearby: ["gidea-park", "romford", "emerson-park", "ardleigh-green", "harold-wood"] },
  { slug: "hornchurch", name: "Hornchurch", postcodes: ["RM11", "RM12"], group: "Romford & Havering", tags: ["family", "interwar", "leafy", "rental"],
    about: "Hornchurch is a historic suburb with a long high street, the Queen's Theatre and a heritage tied to the former RAF Hornchurch airfield.",
    homes: "Interwar semis and terraces, with larger houses around the quieter roads.",
    tip: "A mix of long-term family homes and rented properties means demand for regular, deep and end of tenancy cleans all year round.",
    nearby: ["emerson-park", "elm-park", "upminster", "ardleigh-green", "south-hornchurch"],
    station: "Hornchurch station is on the District line." },
  { slug: "emerson-park", name: "Emerson Park", postcodes: ["RM11"], group: "Romford & Havering", tags: ["leafy", "family"],
    about: "Emerson Park is one of the more sought-after parts of Hornchurch, known for larger homes on tree-lined roads.",
    homes: "Large detached and semi-detached houses are typical.",
    tip: "Bigger homes mean more rooms to cover, so many customers book longer regular sessions or a thorough deep clean to start.",
    nearby: ["hornchurch", "gidea-park", "squirrels-heath", "ardleigh-green", "upminster"],
    station: "Emerson Park station is on the Romford to Upminster line." },
  { slug: "ardleigh-green", name: "Ardleigh Green", postcodes: ["RM11"], group: "Romford & Havering", tags: ["family", "interwar", "leafy"],
    about: "Ardleigh Green sits between Romford and Hornchurch, with quiet residential roads.",
    homes: "Interwar semis and bungalows are common.",
    tip: "Quiet family streets suit a dependable regular clean with a seasonal deep clean.",
    nearby: ["hornchurch", "emerson-park", "squirrels-heath", "gidea-park", "romford"] },
  { slug: "elm-park", name: "Elm Park", postcodes: ["RM12"], group: "Romford & Havering", tags: ["family", "interwar", "leafy", "commuter"],
    about: "Elm Park is a 1930s garden suburb planned around its District line station.",
    homes: "Neat interwar semis and terraces are the main housing style.",
    tip: "Well-kept family homes suit a regular clean to keep bathrooms, kitchens and floors fresh between the weekend jobs.",
    nearby: ["hornchurch", "south-hornchurch", "dagenham-east", "rainham", "upminster"],
    station: "Elm Park station is on the District line." },
  { slug: "south-hornchurch", name: "South Hornchurch", postcodes: ["RM12", "RM13"], group: "Romford & Havering", tags: ["family", "estate", "newbuild"],
    about: "South Hornchurch lies between Elm Park and Rainham, close to the Thames side of the borough.",
    homes: "Interwar houses, post-war estates and newer homes nearby.",
    tip: "A mix of older and newer homes means regular, deep and builders' cleans are all in demand.",
    nearby: ["elm-park", "rainham", "hornchurch", "dagenham-east", "thames-view"] },
  { slug: "upminster", name: "Upminster", postcodes: ["RM14"], group: "Romford & Havering", tags: ["leafy", "village", "commuter", "family"],
    about: "Upminster is a leafy village-style town at the end of the District line, known for its windmill and good rail links.",
    homes: "Larger detached and semi-detached homes, plus quieter flats near the station.",
    tip: "Larger homes and busy households make longer regular cleans and seasonal deep cleans a popular combination.",
    nearby: ["cranham", "hornchurch", "emerson-park", "harold-wood", "rainham"],
    station: "Upminster station has District line, c2c and London Overground services." },
  { slug: "cranham", name: "Cranham", postcodes: ["RM14"], group: "Romford & Havering", tags: ["village", "leafy", "family"],
    about: "Cranham is a quiet, village-like community on the edge of the countryside, close to Upminster.",
    homes: "Mostly semi-detached and detached family houses with gardens.",
    tip: "Family homes with gardens bring muddy boots and pet hair indoors, which regular cleans handle well.",
    nearby: ["upminster", "hornchurch", "emerson-park", "harold-wood", "rainham"] },
  { slug: "rainham", name: "Rainham", postcodes: ["RM13"], group: "Romford & Havering", tags: ["newbuild", "family", "rental"],
    about: "Rainham is a growing Havering suburb on the Thames side, with a c2c station, Rainham Hall and the RSPB Rainham Marshes nearby.",
    homes: "Interwar houses and newer developments sit side by side.",
    tip: "Plenty of new-build homes and rented properties means after builders and end of tenancy cleans are in regular demand.",
    nearby: ["south-hornchurch", "elm-park", "dagenham-east", "upminster", "thames-view"],
    station: "Rainham station has c2c services." },
  { slug: "rush-green", name: "Rush Green", postcodes: ["RM7"], group: "Romford & Havering", tags: ["family", "interwar"],
    about: "Rush Green is a residential neighbourhood between Romford and Dagenham.",
    homes: "Mostly interwar and post-war family houses.",
    tip: "Settled family homes suit a regular clean, with an occasional deep clean for ovens and appliances.",
    nearby: ["romford", "becontree-heath", "dagenham", "marks-gate", "collier-row"] },

  // ── Ilford & Redbridge ────────────────────────────────────────────────
  { slug: "goodmayes", name: "Goodmayes", postcodes: ["IG3"], group: "Ilford & Redbridge", tags: ["rental", "period", "commuter", "flats"],
    about: "Goodmayes is a residential neighbourhood between Ilford and Chadwell Heath with a station on the Elizabeth line.",
    homes: "Victorian and Edwardian terraces dominate, many converted into flats.",
    tip: "Period terraces and converted flats mean plenty of end of tenancy and deep cleaning work as tenants move in and out.",
    nearby: ["seven-kings", "ilford", "chadwell-heath", "newbury-park", "becontree-heath"],
    station: "Goodmayes station is on the Elizabeth line." },
  { slug: "seven-kings", name: "Seven Kings", postcodes: ["IG3"], group: "Ilford & Redbridge", tags: ["rental", "period", "flats", "commuter"],
    about: "Seven Kings is a busy residential area on the Ilford side of the border, with a lively high street and an Elizabeth line station.",
    homes: "Terraced houses and converted flats are the norm here.",
    tip: "With so many rented flats and shared houses, a proper end of tenancy clean is one of the most requested services.",
    nearby: ["goodmayes", "ilford", "newbury-park", "gants-hill", "chadwell-heath"],
    station: "Seven Kings station is on the Elizabeth line." },
  { slug: "ilford", name: "Ilford", postcodes: ["IG1"], group: "Ilford & Redbridge", tags: ["centre", "rental", "flats", "commuter"],
    about: "Ilford is one of east London's major town centres, with large shopping areas and Elizabeth line services.",
    homes: "A mix of Victorian terraces, converted flats and large modern apartment blocks.",
    tip: "A large rental market means landlords, agents and tenants all need dependable end of tenancy and deep cleans.",
    nearby: ["seven-kings", "goodmayes", "gants-hill", "redbridge", "barking"],
    station: "Ilford station is on the Elizabeth line." },
  { slug: "gants-hill", name: "Gants Hill", postcodes: ["IG2"], group: "Ilford & Redbridge", tags: ["family", "interwar", "leafy", "commuter"],
    about: "Gants Hill is known for its roundabout and for its distinctive Central line station designed by Charles Holden.",
    homes: "Interwar semis and 1930s houses, many with generous gardens, line the surrounding roads.",
    tip: "Larger interwar family homes suit weekly or fortnightly cleans that keep on top of kitchens, bathrooms and floors.",
    nearby: ["newbury-park", "redbridge", "ilford", "barkingside", "clayhall"],
    station: "Gants Hill station is on the Central line." },
  { slug: "barkingside", name: "Barkingside", postcodes: ["IG6"], group: "Ilford & Redbridge", tags: ["family", "interwar", "leafy"],
    about: "Barkingside has its own high street and a Central line station, with a calm, residential feel.",
    homes: "Interwar houses and 1930s semis sit alongside newer flats.",
    tip: "Family homes here often want a regular clean plus an occasional deep clean of ovens and appliances.",
    nearby: ["newbury-park", "hainault", "clayhall", "gants-hill", "ilford"],
    station: "Barkingside station is on the Central line." },
  { slug: "newbury-park", name: "Newbury Park", postcodes: ["IG2"], group: "Ilford & Redbridge", tags: ["commuter", "family", "interwar"],
    about: "Newbury Park is a residential area on the Central line, close to Gants Hill and Barkingside.",
    homes: "Mostly 1930s semi-detached houses with gardens, plus some modern flats.",
    tip: "Commuter households tend to book a regular clean on a fixed day each week or fortnight.",
    nearby: ["gants-hill", "barkingside", "seven-kings", "redbridge", "ilford"],
    station: "Newbury Park station is on the Central line." },
  { slug: "redbridge", name: "Redbridge", postcodes: ["IG4"], group: "Ilford & Redbridge", tags: ["commuter", "family", "flats"],
    about: "Redbridge is a residential neighbourhood with a Central line station, between Ilford and Wanstead.",
    homes: "Interwar houses and flats close to the main road.",
    tip: "Households here often balance work and family, so a regular clean on a fixed day is the most popular choice.",
    nearby: ["ilford", "gants-hill", "wanstead", "clayhall", "newbury-park"],
    station: "Redbridge station is on the Central line." },
  { slug: "clayhall", name: "Clayhall", postcodes: ["IG5"], group: "Ilford & Redbridge", tags: ["family", "interwar", "leafy"],
    about: "Clayhall is a quiet residential neighbourhood in the Redbridge area, near Barkingside and Fairlop.",
    homes: "Interwar houses and 1930s semis with gardens.",
    tip: "Settled family homes suit weekly or fortnightly cleans with a deeper clean each season.",
    nearby: ["barkingside", "gants-hill", "redbridge", "hainault", "woodford"] },
  { slug: "hainault", name: "Hainault", postcodes: ["IG6"], group: "Ilford & Redbridge", tags: ["family", "estate", "commuter"],
    about: "Hainault is a residential area close to Hainault Forest Country Park, with a Central line station.",
    homes: "Post-war houses and estates, with some newer homes.",
    tip: "Family homes close to the forest bring in mud and leaves, so regular cleans of floors and entrances make a noticeable difference.",
    nearby: ["barkingside", "clayhall", "chigwell", "newbury-park", "gants-hill"],
    station: "Hainault station is on the Central line." },
  { slug: "woodford", name: "Woodford", postcodes: ["IG8"], group: "Ilford & Redbridge", tags: ["leafy", "family", "village", "commuter"],
    about: "Woodford sits on the edge of Epping Forest, with a Central line station and a mix of suburban and village-style streets.",
    homes: "Large interwar and Edwardian houses are common.",
    tip: "Larger family houses lend themselves to longer regular cleans and a seasonal deep clean.",
    nearby: ["wanstead", "redbridge", "chigwell", "clayhall", "loughton"],
    station: "Woodford station is on the Central line." },
  { slug: "wanstead", name: "Wanstead", postcodes: ["E11"], group: "Ilford & Redbridge", tags: ["period", "leafy", "commuter", "family"],
    about: "Wanstead is a leafy neighbourhood beside Wanstead Flats and Wanstead Park, with its own Central line station.",
    homes: "Handsome Victorian and Edwardian houses and period conversions.",
    tip: "Period homes with sash windows and original floors reward a careful deep clean and a regular maintenance clean.",
    nearby: ["leytonstone", "redbridge", "forest-gate", "manor-park", "woodford"],
    station: "Wanstead station is on the Central line." },

  // ── Newham & East London ─────────────────────────────────────────────
  { slug: "east-ham", name: "East Ham", postcodes: ["E6"], group: "Newham & East London", tags: ["rental", "period", "flats", "centre"],
    about: "East Ham is a vibrant, densely populated area with a long high street and District and Hammersmith & City line stations.",
    homes: "Victorian terraces, many converted to flats, plus newer apartment blocks.",
    tip: "A large private rental market means end of tenancy cleans to agency standard are in constant demand.",
    nearby: ["upton-park", "beckton", "plaistow", "manor-park", "barking"],
    station: "East Ham station has District and Hammersmith & City line services." },
  { slug: "beckton", name: "Beckton", postcodes: ["E6"], group: "Newham & East London", tags: ["newbuild", "flats", "rental"],
    about: "Beckton is a Docklands-edge neighbourhood served by the DLR, with large retail parks and newer housing.",
    homes: "Newer flats and townhouses, many built in recent decades.",
    tip: "Modern flats suit regular cleans, and renters moving on need an end of tenancy clean before handing back the keys.",
    nearby: ["east-ham", "canning-town", "upton-park", "thames-view", "barking"],
    station: "Beckton is served by the DLR." },
  { slug: "plaistow", name: "Plaistow", postcodes: ["E13"], group: "Newham & East London", tags: ["rental", "period", "flats"],
    about: "Plaistow is an inner east London neighbourhood with District and Hammersmith & City line stations.",
    homes: "Victorian terraces and converted flats, plus newer apartment blocks.",
    tip: "Rented flats and shared houses mean end of tenancy and deep cleans are common requests.",
    nearby: ["upton-park", "east-ham", "canning-town", "stratford", "forest-gate"],
    station: "Plaistow station has District and Hammersmith & City line services." },
  { slug: "upton-park", name: "Upton Park", postcodes: ["E13", "E6"], group: "Newham & East London", tags: ["rental", "period", "flats"],
    about: "Upton Park is known for Green Street's shopping and for the former home of West Ham United, the Boleyn Ground.",
    homes: "Victorian terraces and converted flats are typical.",
    tip: "Busy households and rented flats mean regular and end of tenancy cleans are both popular.",
    nearby: ["east-ham", "plaistow", "manor-park", "forest-gate", "beckton"],
    station: "Upton Park station has District and Hammersmith & City line services." },
  { slug: "manor-park", name: "Manor Park", postcodes: ["E12"], group: "Newham & East London", tags: ["rental", "period", "commuter"],
    about: "Manor Park is a residential area between Forest Gate and Ilford, with an Elizabeth line station.",
    homes: "Terraced Victorian and Edwardian houses, many divided into flats.",
    tip: "Terraces and conversions bring a steady flow of tenants, so end of tenancy cleans are a staple here.",
    nearby: ["forest-gate", "upton-park", "east-ham", "ilford", "seven-kings"],
    station: "Manor Park station is on the Elizabeth line." },
  { slug: "forest-gate", name: "Forest Gate", postcodes: ["E7"], group: "Newham & East London", tags: ["rental", "period", "commuter", "flats"],
    about: "Forest Gate is a lively neighbourhood with a high street, Woodgrange Park and Elizabeth line services.",
    homes: "Victorian terraces and conversions, with newer flats nearby.",
    tip: "Period terraces call for thorough deep cleans, and renters moving on need an agency-ready end of tenancy clean.",
    nearby: ["manor-park", "stratford", "upton-park", "plaistow", "wanstead"],
    station: "Forest Gate station is on the Elizabeth line." },
  { slug: "stratford", name: "Stratford", postcodes: ["E15"], group: "Newham & East London", tags: ["centre", "flats", "rental", "newbuild", "commuter"],
    about: "Stratford is a major transport hub next to Westfield Stratford City and Queen Elizabeth Olympic Park.",
    homes: "Modern apartment blocks, many rented, alongside older terraces.",
    tip: "With so many rented apartments, end of tenancy cleans and quick-turnaround deep cleans are in high demand.",
    nearby: ["forest-gate", "plaistow", "canning-town", "leytonstone", "manor-park"],
    station: "Stratford is a major hub for the Central and Jubilee lines, DLR, Elizabeth line and rail." },
  { slug: "canning-town", name: "Canning Town", postcodes: ["E16"], group: "Newham & East London", tags: ["newbuild", "flats", "rental"],
    about: "Canning Town is a fast-changing area with Jubilee line and DLR links and lots of new regeneration.",
    homes: "New apartment blocks beside older council and terraced housing.",
    tip: "Newly built flats often need a builders' clean before move-in, and renters need end of tenancy cleans on the way out.",
    nearby: ["beckton", "plaistow", "stratford", "east-ham", "upton-park"],
    station: "Canning Town station has Jubilee line and DLR services." },
  { slug: "leytonstone", name: "Leytonstone", postcodes: ["E11"], group: "Newham & East London", tags: ["rental", "period", "flats", "commuter"],
    about: "Leytonstone is a creative, busy neighbourhood, known as the birthplace of film director Alfred Hitchcock, with a Central line station.",
    homes: "Victorian terraces and converted flats, with some newer apartments.",
    tip: "Lots of rented flats and house-shares mean end of tenancy cleans are a regular request.",
    nearby: ["wanstead", "stratford", "forest-gate", "manor-park", "redbridge"],
    station: "Leytonstone station is on the Central line." },

  // ── Essex border ──────────────────────────────────────────────────────
  { slug: "chigwell", name: "Chigwell", postcodes: ["IG7"], group: "Essex border", tags: ["leafy", "family", "village"],
    about: "Chigwell is an affluent Essex town just beyond the Redbridge border, with a Central line station and green spaces nearby.",
    homes: "Large detached houses and executive homes are common.",
    tip: "Larger properties often need longer sessions, so many customers book a regular clean plus an annual deep clean.",
    nearby: ["woodford", "hainault", "clayhall", "loughton", "barkingside"],
    station: "Chigwell station is on the Central line." },
  { slug: "loughton", name: "Loughton", postcodes: ["IG10"], group: "Essex border", tags: ["leafy", "family", "commuter", "village"],
    about: "Loughton is an Essex town on the edge of Epping Forest with a Central line station and a lively high street.",
    homes: "Large family homes and flats near the station.",
    tip: "Larger family homes suit regular cleans and a thorough seasonal deep clean.",
    nearby: ["chigwell", "woodford", "hainault", "clayhall", "barkingside"],
    station: "Loughton station is on the Central line." },
];

/** Areas currently published. */
export const AREAS: Area[] = ALL_AREAS.filter((a) => a.enabled !== false);

const BY_SLUG = new Map(AREAS.map((a) => [a.slug, a]));
export const getArea = (slug: string): Area | undefined => BY_SLUG.get(slug);

/** Neighbouring areas that are themselves published. */
export const nearbyAreas = (area: Area): Area[] => area.nearby.flatMap((s) => (BY_SLUG.has(s) ? [BY_SLUG.get(s)!] : []));

export const AREA_GROUPS: AreaGroup[] = ["Barking & Dagenham", "Romford & Havering", "Ilford & Redbridge", "Newham & East London", "Essex border"];
